#!/bin/bash

BROKER_CONFIG_FILE="/opt/rocketmq-$ROCKETMQ_VERSION/conf/broker.conf"
echo $BROKER_CONFIG_FILE

BROKER_ID=$(cat /etc/hostname | grep -o '[^-]*$')

BROKER_ROLE="SLAVE"

if [ $BROKER_ID = 0 ];then
    if [ $REPLICATION_MODE = "SYNC" ];then
      BROKER_ROLE="SYNC_MASTER"
    else
      BROKER_ROLE="ASYNC_MASTER"
    fi
fi

function gen_config() {
    rm -f $BROKER_CONFIG_FILE
    echo "Creating broker configuration."
    echo "#This file was auto generated by rocketmq-operator. DO NOT EDIT." >> $BROKER_CONFIG_FILE
    env | grep 'ROCKETMQ_CONFIG_' | sed s/ROCKETMQ_CONFIG_//g >> $BROKER_CONFIG_FILE
    echo "Wrote broker configuration file to $BROKER_CONFIG_FILE as below..."
    cat $BROKER_CONFIG_FILE
}

gen_config